apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    nodePort: 30080
    name: http
  selector:
    app: nginx
